###
GET http://localhost:3030/usuarios

###
GET http://localhost:3030/usuarios/1

### 
POST http://localhost:3030/usuarios
Content-Type: application/json

{
    "nombre": "luis",
    "email": "luis@gmail.com"
}
